import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';
import HydrationBoundaryWrapper from '@/lib/providers/hydration';
import TanstackProvider from '@/lib/providers/queryclient-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <HydrationBoundaryWrapper>
            <main>{children}</main>
            <Toaster />
          </HydrationBoundaryWrapper>
        </TanstackProvider>
      </body>
    </html>
  );
}
